### ISSUE TITLE
The remote server returned an unexpected response: (413) Request Entity Too Large

### ISSUE THREAD

**Issue by lumalav** [chgeuer/AzureLargeFileUploader#1]
I tried modifying the numBytesPerChunk value. However, it throws the exception for anything larger than 100mb.

**Comment by chgeuer** [comment]
mumBytesPerChumk has a maximum of 4MB. That's a design choice of the Azure Blob Storage API. numBytesPerChunk defines the size of an HTTP POST Upload (and of an Azure storage BLOCK (not blob)). ["Each block can be a different size, up to a maximum of 4 MB, and a block blob can include up to 50,000 blocks."](https://msdn.microsoft.com/en-us/library/azure/ee691964.aspx)
